### ISSUE TITLE
Scale tests todo:

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1039]
In no particular order, probably missing some:
- [ ] Get Metrics working.
- [ ] Add metric for tickets created / deleted / assigned.
- [ ] Add metric for matches received / assigned.
- [ ] Add metric for proportion of matches pass evaluation.
- [ ] Add metric for mmlogic query time?
- [ ] Add metric for iteration cycle time.
- [ ] Add extension to tickets with start time, add metric for ticket lifetime on matched.
- [ ] If possible, add metric for current ticket pool age lifetimes.
- [ ] Add mode for waiting for assignments on the frontend.
- [ ] Make frontend ticket creation a Poisson distribution.
- [ ] Add scenario for running the whole pool through one mmf (ala firstmatch).
- [ ] Add scenario for skill based matchmaking with regions and gamemodes.
- [ ] Report the scenario's running stats for various improvement proposals.

**Comment by sawagh** [comment]
Can we move this to v0.10 or do we expect anything more here today?

**Comment by Laremere** [comment]
- [ ] Add an optional delay between ticket being in a match, and getting assigned.  In a real world scenario, a significant number of tickets might be in a pending state because getting servers takes some time.

**Comment by yfei1** [comment]
Moving this to v0.10

**Comment by Laremere** [comment]
Rundown of scenarios I want to run:

Breaking down the scale test into two halves:
logical scenario: The MMF, Evaluator, tickets, and profiles.
3 flavors:
- First Match: one profile, mmf pairs tickets, drains pool with no special logic.
- Battle Royal: 20 regional profiles, tickets choose one region to search in.  Matches of 100 players are made.
- Team Shooter: profiles are split on region, mode, and skill ranges.  Tickets have a random skill, one or few regions, and one mode.  Match function groups tickets with similar skill, evaluator ranks by lowest skill difference.  Configurable number of regions, modes, skill splits.

infra scenario: How Open Match is being called.
Flavors:
- (infra1) Frontend client creates tickets, backend client directly deletes tickets.
- (infra2) Frontend client creates tickets then polls for assignment before deleting the ticket.  Backend assigns tickets.
- (infra3) Frontend client creates tickets then uses wait for assignment before deleting the ticket.  Backend assigns tickets.

List of scenarios I want to run:
- The "control" scenario.  Team shooter with a ~10 profiles, using infra1.
- control, but with first match instead
- control, but with battle royal instead
- control, but with team shooter having ~100 profiles.
- control, but with team shooter having ~1000 profiles.
- control, but with infra 2
- control, but with infra 3

That's 7 scenarios.

**Comment by Laremere** [comment]
Per discussion:
Logical Scenario will become GameScenario.
Infra Scenario will become UsagePattern.
